### ISSUE TITLE
[QUESTION] Serve assets only to logged in users

### ISSUE THREAD

**Issue by eHonnef** [Lissy93/dashy#1466] opened 2024-02-18 13:20 UTC
### Question

Hello,

Currently I'm using dashy container with keycloak authentication behind NGINX, and I'm trying to have some `.html` static files served inside the workspace, e.g.: files generated by goaccess.

But, when I access http://mydash.example.com/goaccess_output.html, it doesn't ask for authentication, it just give the information.

The same is valid if you http://mydash.example.com/conf.yml, it will return the content of conf.yml, that's a little concerning if you are using, for example, glances with the password.

Maybe I'm missing some configuration, could you give me some help?

Thanks so far.

### Category

Authentication

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment] 2024-02-19 16:17
Duplicate of #668

**Comment by CrazyWolf13** [comment] 2024-02-19 16:19
This is currently true but will be adressed while rewriting how the backend handels the config file.

**Closed** 2024-02-19 16:20 UTC
Labels: 🕸️ Duplicate, 🤷‍♂️ Question
