### ISSUE TITLE
font-awesome icons only work if there's no dash in the icon name

### ISSUE THREAD

**Issue by don-ferris** [Lissy93/dashy#1612] opened 2024-06-05 19:59 UTC
### Environment

Self-Hosted (Docker)

### System

Mint 21.3 Xfce

### Version

3.1.1

### Describe the problem

For Sections or items, any font-awesome icon that has a dash in the name results in no icon being displayed. Any icon with no dash in the name works fine.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment] 2024-06-05 20:05
Hi

Yeah this is a duplicate of https://github.com/Lissy93/dashy/issues/1077

Which will be adressed in https://github.com/Lissy93/dashy/issues/1424

**Closed by CrazyWolf13** 2024-06-05 20:05 UTC
Labels: 🐛 Bug

**Comment by don-ferris** [comment] 2024-06-06 18:42
> Yeah this is a duplicate of #1077
> 
> Which will be adressed in #1424

Sorry, I did search but I guess I missed that. Any idea when 1424 will be out?

**Comment by CrazyWolf13** [comment] 2024-06-06 19:08
@don-ferris  

No problem, they are sometimes hard to spot :)

Sorry, no idea and no ETA, lissy is currently a bit busy as she got chosen for Github Accelerator 2024.
