### ISSUE TITLE
[BUG] Press Enter to log in

### ISSUE THREAD

**Issue by Andrewpaps** [Lissy93/dashy#484] opened 2022-02-08 18:57 UTC
### Environment

Self-Hosted (Docker)

### Version

2.0.2

### Describe the problem

At the moment pressing Enter after entering authentication credentials at log in is not connecting to a form confirmation action. It would be nice not to have to reach for the mouse here :)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment] 2022-02-15 06:24
Closing as duplicate of #483

**Closed by Lissy93** 2022-02-15 06:24 UTC
Labels: 🐛 Bug
