### ISSUE TITLE
[QUESTION] Saved config to file was lost

### ISSUE THREAD

**Issue by Coder84619** [Lissy93/dashy#1292] opened 2023-08-19 15:42 UTC
### Question

New to Dashy. I built a nice dashboard, and on several occasions I did "save to disk". However, I refreshed my browser and ALL of my work was GONE. 

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by zaromarco** [comment] 2023-08-20 15:46
Did you use docker?

**Comment by Coder84619** [comment] 2023-08-20 20:35
> 

No. I used the tteck Proxmox LXC install script.

**Comment by zaromarco** [comment] 2023-08-20 23:50
Ah ok . I don't know lxc container. In docker for example you need to bind an external config yaml file needed to override the same config file inside the container .
With that you will be able to use "save to disk" the configuration done , maybe in lxc the concept is the same...

**Comment by coldlamper** [comment] 2023-09-10 08:39
I have the same issue.  After losing my changes many, many times, I figured out if you click preview changes then save to disk then the ./public/config.yml gets updated as expected. Clicking Save Changes under Edit Config seems to do nothing. 
To see the changes after reloading the page you I needed to rebuild application.

Seems like there might be 2 bugs here, The Save Changes doing nothing and the rebuild not automatically happening

It's pretty confusing for first time users if this is not a bug.

**Comment by Pyro2677** [comment] 2023-10-22 13:31
> I have the same issue. After losing my changes many, many times, I figured out if you click preview changes then save to disk then the ./public/config.yml gets updated as expected. Clicking Save Changes under Edit Config seems to do nothing. To see the changes after reloading the page you I needed to rebuild application.
> 
> Seems like there might be 2 bugs here, The Save Changes doing nothing and the rebuild not automatically happening
> 
> It's pretty confusing for first time users if this is not a bug.

For me I had to click save local and then go back in and save to disk. I thought I would give this a try but Dashy just isn't easy. I'm going back to Homepage.

**Comment by CrazyWolf13** [comment] 2024-02-24 22:18
Thiss seems like a duplicate of #1147 

Look here for a detailed explanation and fix.
https://github.com/Lissy93/dashy/issues/1147#issuecomment-1962388094

**Closed** 2024-02-24 22:18 UTC
Labels: 🕸️ Duplicate, 🤷‍♂️ Question
