### ISSUE TITLE
[FEATURE_REQUEST] Alternative service URL for remote access

### ISSUE THREAD

**Issue by Spatchy** [Lissy93/dashy#1313] opened 2023-09-13 13:20 UTC
### Is your feature request related to a problem? If so, please describe.

For remote access on my setup, I use Tailscale. Tailscale assigns each node in the network an IP that can only be accessed when connected to your "tailnet" virtual network; local IPs and DNS resolution doesn't work when accessing pages when connected. This means that the service URLs defined for items in Dashy do not work when the Dashy is accessed remotely.

### Describe the solution you'd like

I propose a new optional field that can be added to the item: "Alternative Service URL" which would be triggered instead if Dashy is being viewed from a different url. A list of "Remote Access URLs" which would trigger the alternative service URL for the item would need to be added to the config.

For clarity, this is how I imagine this being used:

- I add `100.90.80.1` to the "Remote Access URLs" List
- I add an "Alternative Service URL" `100.90.80.1:8999` to one of my items
- When accessing Dashy via `myserver.local`, nothing is different, the regular "Service URL" is used
- When accessing Dashy via `100.90.80.1` and I click on my item, the "Alternative Service URL" is used instead

Dashy can now work locally and remotely when used with Tailscale or a similar VPN-based solution.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

Maybe

**Comment by CrazyWolf13** [comment] 2023-11-01 19:14
> ### Is your feature request related to a problem? If so, please describe.
> For remote access on my setup, I use Tailscale. Tailscale assigns each node in the network an IP that can only be accessed when connected to your "tailnet" virtual network; local IPs and DNS resolution doesn't work when accessing pages when connected. This means that the service URLs defined for items in Dashy do not work when the Dashy is accessed remotely.
> 
> ### Describe the solution you'd like
> I propose a new optional field that can be added to the item: "Alternative Service URL" which would be triggered instead if Dashy is being viewed from a different url. A list of "Remote Access URLs" which would trigger the alternative service URL for the item would need to be added to the config.
> 
> For clarity, this is how I imagine this being used:
> 
> * I add `100.90.80.1` to the "Remote Access URLs" List
> * I add an "Alternative Service URL" `100.90.80.1:8999` to one of my items
> * When accessing Dashy via `myserver.local`, nothing is different, the regular "Service URL" is used
> * When accessing Dashy via `100.90.80.1` and I click on my item, the "Alternative Service URL" is used instead
> 
> Dashy can now work locally and remotely when used with Tailscale or a similar VPN-based solution.
> 
> ### Priority
> Medium (Would be very useful)
> 
> ### Is this something you would be keen to implement
> Maybe

This is a duplicate of https://github.com/Lissy93/dashy/issues/820 Please close this.

**Closed** 2023-11-03 13:42 UTC
Labels: 🦄 Feature Request, 👤 Awaiting Maintainer Response
