### ISSUE TITLE
Unable to get Proxmox list widget to work

### ISSUE THREAD

**Issue by ImChet** [Lissy93/dashy#1317] opened 2023-09-16 00:05 UTC
### Discussed in https://github.com/Lissy93/dashy/discussions/1315

<div type='discussions-op-text'>

<sup>Originally posted by **ImChet** September 14, 2023</sup>
Error:
```
An error occurred, see the logs for more info.

Unable to fetch data
```
Here is the code block for my proxmox-list:

```
sections:
  - name: Server Management
    icon: ''
    items:
      - title: xxxxxxxxxx
        description: ''
        icon: hl-proxmox
        url: xxxxxxxxxx
        target: newtab
        id: xxxxxxxx
      - title: xxxxxxxxx
        icon: hl-proxmox
        url: xxxxxxxxxxx
        target: newtab
        id: xxxxxxxx
      - title: xxxxxxxx
        icon: hl-truenas
        url: xxxxxxxxxx
        target: newtab
        id: xxxxxxx
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: true
    widgets:
    - type: proxmox-lists
      useProxy: true
      options:
        cluster_url: https://x.x.x.x:xxxx
        user_name: root@pam
        token_name: dashy
        token_uuid: xxxxxxxxxxxxxxxxxxxxxxxx
```</div>

**Comment by ilium007** [comment] 2023-09-30 11:42
Searched and found this issue before creating the same. No VM data is listed. If I put an intentionally wrong value in for node the widget throws an error so I can only assume that with the correct value and no error on screen it is gettign data back from the API but not parsing it correctly.

**Comment by ilium007** [comment] 2023-09-30 11:44
This is the JSON from the constructed API call in the browser:

`{"data":[{"mem":7728077790,"diskread":0,"maxmem":8589934592,"cpu":0.0041496411882829,"status":"running","diskwrite":0,"pid":2374150,"disk":0,"name":"omv01","netin":0,"vmid":103,"cpus":2,"netout":0,"uptime":22400,"maxdisk":34359738368},{"netin":0,"disk":0,"name":"debian01","diskwrite":0,"status":"running","pid":791159,"cpu":0.0117877760698244,"maxdisk":34359738368,"netout":0,"cpus":4,"uptime":364263,"vmid":101,"mem":5502137380,"maxmem":8589934592,"diskread":0},{"mem":0,"maxmem":4294967296,"diskread":0,"name":"windows11","disk":0,"netin":0,"cpu":0,"status":"stopped","diskwrite":0,"uptime":0,"cpus":2,"netout":0,"maxdisk":34359738368,"vmid":102}]}`

**Comment by nortuzar** [comment] 2023-10-11 17:50
Same problem here, fresh install of dashy and couldnt make this widget work.
Anyway im enjoying dashy very much

**Comment by wnaude** [comment] 2024-01-13 10:09
Hi, I also struggled at first, but then I changed the permissions of the API token in the datacenter web gui. Unticked the privilege separation., then the "show permissions" section got populated where it was empty before. I am a noob, so I must still go rtfm on the detail of what it means and what the risks are.
Just dropping the note incase it might help someone.

**Comment by lumper5** [comment] 2024-01-19 00:25
No luck here getting this widget to connect. I had hopes that the "privilege separation" would work (it was the solution to a similar problem in homepage and Heimdall).  I wonder what the trick is to get this to authenticate?

**Comment by Lissy93** [comment] 2024-02-27 23:04
I don't think I'm going to be much help here, as I didn't build the Proxmox widget, and I don't have a Proxmox instance to test with. But what does the error message in the browser logs say? ([here's how to check](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console))

**Comment by CrazyWolf13** [comment] 2024-03-03 18:20
@alayham Could you take over here?

**Comment by alayham** [comment] 2024-03-04 19:15
Gladly. I have a video that shows how to install a development environment for Dashy and install the widget to fix a bug in it. I also added documentation to handle the common errors I faced with the widget.
please look at my video here:
https://www.youtube.com/watch?v=6H9j2OFr69U&list=PLZLlJrtYGHany2Mvz-Q59SPeWp88iESU1&index=8

The documentation for the errors is in the repo, but not visible on the documentation site.
https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#proxmox-lists

![image](https://github.com/Lissy93/dashy/assets/518776/b98528cf-4e9c-49ae-a3cb-a98a547bfa5f)

**Suggestions for users:**

1. Make sure you use Dashy in production mode.
2. Make sure PVE certificate is trusted by nodejs on the host that runs Dashy.

**Comment by alayham** [comment] 2024-03-11 10:34
@ilium007 @ImChet @nortuzar @wnaude 
Were you able to resolve the issue with the information above?

**Comment by CrazyWolf13** [comment] 2024-03-12 19:43
Hi @alayham  Sadly I could not resolve the issue with the info provided above and in the docs.

Sadly the part how to extract the CA is compledtely missing, did you forget that?!

By manually clicking "view" on the root ca I could see the CA key, I copy pasted it to a file and did the export command with my path, sadly even after a reboot and rebuild of dashy I'm still getting the error code: axios request failed with status code 500

Is it really neccessary for everyone to extract that certificate?

**Comment by alayham** [comment] 2024-03-16 09:15
Yes, It is necessary unless the Proxmox VE uses a trusted certificate. The reason is that Nodejs has a list of trusted certificates authority compiled inside the binary, and will only accept them for security. We have the ability to add to them using the following process:
1- Visit the certificates page of your PVE, you should see at lease two certificates, one ends with -ca.pem, click on it.
2- click on View Certificate
3- click on Raw certificate
![image](https://github.com/Lissy93/dashy/assets/518776/32307f2b-6b12-4607-ba08-40cb792fd6e0)

4- Copy everything in the text area below View Certificate and paste it into a file called pve-root-ca.pem
5- Move the file to your Dashy host.
Either:
6- start dashy with `NODE_EXTRA_CA_CERTS=<path of the copied file> yarn start`
or
6- A a line to the file .bash_profile in the home directory of the user that run dashy containing: `export NODE_EXTRA_CA_CERTS=<path of the copied file>` and restart the shell session for the export to be active, then start Dashy using `yarn start`
You can watch my [video](https://www.youtube.com/watch?v=6H9j2OFr69U&list=PLZLlJrtYGHany2Mvz-Q59SPeWp88iESU1&index=8) about setting up Dashy using Ansible, or read this [article](https://medium.com/@al-saleh/building-a-node-js-development-container-with-ansible-f916a89241e6) about the subject.

**Comment by CrazyWolf13** [comment] 2024-03-16 12:58
I set everything up according to your guide above, but I cannot seem to get it working.

Does Dashy have to have a certificate and run with https /ssl ?
Because currently mine runs in http mode.

Also is it okay to use the IP instead of a domain name for the cluster url?

Here a little screenshot.

![image](https://github.com/Lissy93/dashy/assets/96661824/d783525b-0484-43fc-b31a-06226e67f750)

My config:

```
  - type: proxmox-lists
    useProxy: true
    options:
      cluster_url: https://10.50.20.10:8006
      user_name: root@pam
      token_name: dashy
      token_uuid: {token}

````

Thanks.-

**Comment by alayham** [comment] 2024-03-18 13:00
Timeout is usually a firewall issue. Can you access the cluster from the Dashy host using `curl`? try 
`curl https://10.50.20.10:8006` from the dashy host. Install `curl` if missing.

**Comment by CrazyWolf13** [comment] 2024-03-18 21:27
> Timeout is usually a firewall issue. Can you access the cluster from the Dashy host using `curl`? try 
> `curl https://10.50.20.10:8006` from the dashy host. Install `curl` if missing.

Seems to work just fine when pinging and curl works if I add -k (think that was to ignore self signed cert) `curl -k https://10.50.20.10:8006`

**Comment by CrazyWolf13** [comment] 2024-03-22 18:58
> replace YOURAPITOKEN with your token in the following command after dashy= and before the single quote, then run run the command on the dashy host and put the response here.

Hi, Thank you!

Yes as stated above, dashy is not running in SSL mode and Proxmox currently only has it's self signed cert.

Host of Dashy is a raspberrypi running raspbian.

Here the result which seems that you guess with the cert not being trusted is true;
```
pi@raspberrypi:~ $ curl  -H 'Authorization: PVEAPIToken=root@pam!dashy=YOURAPITOKEN' https://10.50.20.10:8006/api2/json/nodes/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Maybe it would also be worth to include all those steps you describe in the docs, as I'm pretty sure others will run into this as well :)

**Comment by alayham** [comment] 2024-03-22 22:06
My first suggestion is to trust the PVE root certificate on the PI. Here are some ideas from StackOverflow:
https://raspberrypi.stackexchange.com/questions/76419/entrusted-certificates-installation

how do you start Dashy? can you paste the command to start Dashy here?

**Comment by CrazyWolf13** [comment] 2024-03-23 09:59
> My first suggestion is to trust the PVE root certificate on the PI. Here are some ideas from StackOverflow: https://raspberrypi.stackexchange.com/questions/76419/entrusted-certificates-installation
> 
> how do you start Dashy? can you paste the command to start Dashy here?
> 
> We can update the documentation after we solve your issue.

I use a "standard" Docker installation, so I added the ca the following way:
Create the ca file on host, map it with a bind volume to the container, verify it's there.

Then add the ENV variable:
![image](https://github.com/Lissy93/dashy/assets/96661824/5b29dc0b-e2ed-45cd-81af-23b1fcb1787f)
Rebuild and restart dashy, notice the wdiget is still not loading.

I unsure where I have to add this cert, in dashy, in the container, in docker or in the host? I guess the container?
Found this thread: https://unix.stackexchange.com/questions/464484/install-self-signed-certificate-to-alpine-linux#:~:text=%2Fetc%2Fssl%2Fcerts%2Fca%2Dcertificates.

So I edited the bind mount to point to `/usr/local/share/ca-certificates/proxmox_ca.pem` and removed the node env variable.
The file /etc/ssl/certs/ca-certificates.crt now contains the cert, however dashy widget is still not working.

**Comment by alayham** [comment] 2024-03-23 12:31
In this case your Dashy host is not the PI, it is the docker engine. There are many things that can go wrong with such setup, and it is not easy to troubleshoot. I will do my best.

1- Can you open a shell to the Dashy container and try to curl the PVE api? 
2- Inside that shell, can you do `cat /app/public/proxmox_ca.pem` to make sure the cert is mounted, and compare it to the original cert on the PVE.
3- In that shell, can you access the outside world, like curl GitHub or the Dashy site?

You might need to install curl in the docker container.

**Comment by CrazyWolf13** [comment] 2024-03-23 13:22
> In this case your Dashy host is not the PI, it is the docker engine. There are many things that can go wrong with such setup, and it is not easy to troubleshoot. I will do my best.
> 
> 1- Can you open a shell to the Dashy container and try to curl the PVE api? 2- Inside that shell, can you do `cat /app/public/proxmox_ca.pem` to make sure the cert is mounted, and compare it to the original cert on the PVE. 3- In that shell, can you access the outside world, like curl GitHub or the Dashy site?
> 
> You might need to install curl in the docker container.


1- Yes, but it still gives me the same error:
```
curl: (60) SSL: no alternative certificate subject name matches target host name '10.50.20.10'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

2- Yes as stated above, the CA is there and contains the same cert, it's even in the `/etc/ssl/certs/ca-certificates.crt` included

3- Yes I can access outside world from dashy container

**Comment by alayham** [comment] 2024-03-23 13:53
I think the docker image is built using the `Dockerfile` in the root directory of the repo
https://github.com/Lissy93/dashy/blob/master/Dockerfile
It seems to build Dashy using node16, and run it using node20. I am not sure how that will impact the code.

It is not enough to put the cert in the container, it needs to be trusted, and you need to trust it every time you start the container unless you change the image. Besides, It seems that Dashy uses a base image of Nodejs that is based on Alpine Linux. On Alpine trusting the certificate is different from Raspian. Here is a StackOverflow link:
https://superuser.com/questions/1430089/how-to-add-a-self-signed-ssl-certificate-to-linux-ubuntu-alpine-trust-store
By the bottom of the answer you see how to trust a cert in Alpine. Notice that the cert needs to be in PEM format, and to have a .crt extension.

After you trust the CA certificate, can you curl the PVE API again from inside the container?

Also, Can you execute the following command inside the container: `set | grep "/app/public/proxmox_ca.pem"` and paste the output here?

**Comment by CrazyWolf13** [comment] 2024-03-23 14:09
I don't really think the other engine is a problem, as I could also not get it to work on a debian build from source machine.

So I have now two bind mounts, one to /usr/local/share/ca-certificates/proxmox.crt, which is the same ca file just with crt extension, the other goes inside the /app/public

installing update-ca-certificates, installs fine but I do not get any output when run.

Do I have to specify the ip of the cert anywhere? as curl states t could not find an external cert for that ip, do I  have to somewhere write that ip?

Here the output:
```/app # set | grep "/app/public/proxmox_ca.pem"
NODE_EXTRA_CA_CERTS='/app/public/proxmox_ca.pem'```

**Comment by alayham** [comment] 2024-03-23 14:33
> installing update-ca-certificates, installs fine but I do not get any output when run.
You should see 1 cert added. If you do not see it then the cert is not added. Try deleting the PVE CA cert, running `update-ca-certificates`, then add the PVE CA cert, and update again. 
If still you do not see a log of 1 added, them maybe the cert file is corrupted, make sure it is identical to the original. Depending on the system, you might need to add a new line at the end of the file. If you are using windows to copy the file, you need to set the newline character to the Linux new line, not the Windows new line.
This StackOverflow answer shows how to list installed certificates on Alpine. You need to make sure the cert is installed correctly and to test to curl the PVE API from the container shell without issues. Not because that solves the node problem but because it is easier to troubleshoot certificate issues this way. Once we have a certificate that we know to work, we can see why NodeJs does not accept it.

> I could also not get it to work on a debian build from source machine
I can help you a lot more in this setup, and my video and article are exactly about this scenario. In the video I show how the cert did not work, and how I fixed it.

**Comment by CrazyWolf13** [comment] 2024-03-23 14:56
Thanks for the help, but sadly no matter what I do I cannot get update-ca-certificates to give me any output.

Installed exactly as shown in the url but I do not get an output. Also i can't really find anything about the no output part on the web.

Also is there really no way to get an "allow insecure" flag?

currently this is an extremely complicated with mounting binding and installing things inside a container which will be gone on reboot etc.

**Comment by alayham** [comment] 2024-03-23 16:24
> Also is there really no way to get an "allow insecure" flag?

Nodejs has its trusted certificates compiled inside the binary. I don't know if we can configure it to ignore certificate trust, and I would not advise you to do that.

> Thanks for the help, but sadly no matter what I do I cannot get update-ca-certificates to give me any output.

Most probably the problem is in the CA certificate file. Let me know if you want to keep working on this until you solve your problem.

**Comment by CrazyWolf13** [comment] 2024-03-23 17:54
> > Also is there really no way to get an "allow insecure" flag?
> 
> Nodejs has its trusted certificates compiled inside the binary. I don't know if we can configure it to ignore certificate trust, and I would not advise you to do that.
> 
> > Thanks for the help, but sadly no matter what I do I cannot get update-ca-certificates to give me any output.
> 
> Most probably the problem is in the CA certificate file. Let me know if you want to keep working on this until you solve your problem.

I'd love to get it working, as the widget looks awesome !

Well if there would be an issue with the file shouldn't there still at least be some output like 0 added or so?

**Comment by alayham** [comment] 2024-03-25 16:04
My approach to this issue is the following: 
1- Confirm that the certificate works, and for this I wanted curl to recognize it because it is a lot easier to troubleshoot. Since we can not confirm that is working on the system, let's try to add it manually to curl. Here is the command, replace YOURCACERTFILE with the path of the PEM cert, and YOURAPITOKEN with the API token:
```
curl --cacert YOURCACERTFILE  -H 'Authorization: PVEAPIToken=root@pam!dashy=YOURAPITOKEN' https://10.50.20.10:8006/api2/json/nodes/ 
```
When we know the CA cert works, we can see why NodeJS does not recognize it.

**Comment by CrazyWolf13** [comment] 2024-03-26 21:02
Sadly still fails. The more I read this, the more I think it has to do with the name, it specifically says it has not found any certificate that matched 10.50.20.10, however neither my cert name nor inside the cert there is the ip specified, where would I have to specify the IP?
````
curl: (60) SSL: no alternative certificate subject name matches target host name '10.50.20.10'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
````

**Comment by alayham** [comment] 2024-03-27 20:08
Aha, This is very good news.
Now we know the error. This means the CA certificate works, but you are calling the server with a domain name that does not exist in the Subject Alternative Names field of your server certificate. I do not have this issue because I use my own certificate authority and I run my own DNS service in my devlab.
Here is an example of what I have in my server:
![image](https://github.com/Lissy93/dashy/assets/518776/ae442e12-02c0-493c-9b8b-912987635f93)

You can see this if you inspect the certificate, and you can see it also in the PVE web admin when you click on the node, and select certificates:
![image](https://github.com/Lissy93/dashy/assets/518776/e09464e6-3b19-44c3-a36f-d0c1e6491aed)

To solve your issue, you need to:
1- Determine the Subject Alternative names of your server's certificate. You can do that by either inspecting the server certificate, or checking the certificates page in your PVE.
2. Make sure those DNS names resolve to the server IP in your network: You can try passing those names to the `nslookup` command, and the command should return the server IP.
3. Make sure those DNS names resolve to the server IP inside the Docker container. Here you might need to replace the IP with a name that resolves in the previous curl command.
4. Update your widget in the Dashy conf to use any name in the SAN field that resolves to the server IP, rebuild Dashy, and let me know if you get an error.

**Comment by CrazyWolf13** [comment] 2024-03-28 20:34
Okay so a little update on this I dug a lot deeper into this and found out, due to me once changing from a simple ip to 10x network the cert had the old ip included, so I regenerated them to official proxmox commands. So I thought I finally finally solved it, however I still get the same exact error.

Here the alternative names:
![image](https://github.com/Lissy93/dashy/assets/96661824/71298ece-4fa9-4451-a8bc-55a3b937e434)

So I cannot use the direct ip 10.50.20.10 ?

**Comment by alayham** [comment] 2024-03-29 11:10
1- Try to use `lenovo1` or `lenovo1.home` instead of the IP in the conf file
2- Try to edit /etc/hosts **inside the container**, and add the something like:
```
10.50.20.10     lenovo1
10.50.20.10     lenovo1.home
```
then rebuild Dashy and try again

**Comment by CrazyWolf13** [comment] 2024-03-29 11:42
Okay, edited the hosts file, ping works.
Traceroute resolves perfectly fine.

When trying to execute the same curl command or with lenovo1 or lenovo1.home i just get straight up no output to cli at all.

Even disabled the proxmox firewall compledtely, still no output to curl at all. Visiting the url in browser on raspberrypi works just fine.

**Comment by alayham** [comment] 2024-03-29 17:06
There is a huge difference between no output (got an empty response) and no output (timeout, or no response at all)

Which one do you get?

Did you test the widget?

**Comment by CrazyWolf13** [comment] 2024-03-29 18:02
> There is a huge difference between no output (got an empty response) and no output (timeout, or no response at all)
> 
> Which one do you get?
> 
> Did you test the widget?
Not sure.

But curl with debug seems to show promising results.
Also the widget does obv. not yet work, as the import did not work.
```
curl  --cacert /app/public/proxmox_ca.pem  -v -H 'Authorization: PVEAPIToken=root@pam!dashy={api_key}' https://10.50.20.10:8006/api2/json/nodes/
*   Trying 10.50.20.10:8006...
* Connected to 10.50.20.10 (10.50.20.10) port 8006
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /app/public/proxmox_ca.pem
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: OU=PVE Cluster Node; O=Proxmox Virtual Environment; CN=lenovo1.home
*  start date: Mar 27 20:22:17 2024 GMT
*  expire date: Mar 27 20:22:17 2026 GMT
*  subjectAltName: host "10.50.20.10" matched cert's IP address!
*  issuer: CN=Proxmox Virtual Environment; OU={some_key}; O=PVE Cluster Manager CA
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> GET /api2/json/nodes/ HTTP/1.1
> Host: 10.50.20.10:8006
> User-Agent: curl/8.5.0
> Accept: */*
> Authorization: PVEAPIToken=root@pam!dashy={api_key}
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 401 invalid token value!
< Cache-Control: max-age=0
< Connection: close
< Date: Fri, 29 Mar 2024 17:59:43 GMT
< Pragma: no-cache
< Server: pve-api-daemon/3.0
< Expires: Fri, 29 Mar 2024 17:59:43 GMT
<
* Closing connection
* TLSv1.3 (OUT), TLS alert, close notify (256):
````

**Comment by CrazyWolf13** [comment] 2024-03-29 18:04
Edit: After regenerating the api_key on proxmox it now outputs the api data. Probably due to ssl cert change.

**Comment by alayham** [comment] 2024-03-29 18:54
> < HTTP/1.1 401 invalid token value!

Where did you run the command? Did you open a shell session inside the Dashy container?

> Surprisingly curl even outputs the data when not specifiying the cert file, so the import seems also successful.

Because the CA cert is trusted on the host that you ran the command on. Is it the Dashy container or the PI?

> However dashy is not working, e.g. still the same error.

Can you past the widget code in your conf, and the output of this command ` set | grep NODE_EXTRA_CA_CERTS` inside the Dashy container.

**Comment by CrazyWolf13** [comment] 2024-03-29 20:19
> Where did you run the command? Did you open a shell session inside the Dashy container?

This is probably only because the api-key was outdated as described in the edit.

> Because the CA cert is trusted on the host that you ran the command on. Is it the Dashy container or the PI?

I run it on the docker container so dashy host.

> Can you paste the widget code in your conf, and the output of this command ` set | grep NODE_EXTRA_CA_CERTS` inside the Dashy container.

Output:
```
/app # set | grep NODE_EXTRA_CA_CERTS
NODE_EXTRA_CA_CERTS='/app/public/proxmox_ca.pem'
```

Here the widget code:

````yaml
      - type: proxmox-lists
        useProxy: true
        options:
          cluster_url: https://10.50.20.10:8006
          user_name: root@pam
          token_name: dashy
          token_uuid: {api_key}
        id: 1_1782_proxmoxlists
````

**Comment by alayham** [comment] 2024-03-30 09:47
You are not following my advice!!

Here is what you I suggest you do again:
1- Determine the Subject Alternative names of your server's certificate. You can do that by either inspecting the server certificate, or checking the certificates page in your PVE.
2. Make sure those DNS names resolve to the server IP in your network: You can try passing those names to the nslookup command, and the command should return the server IP.
3. Make sure those DNS names resolve to the server IP inside the Docker container. Here you might need to replace the IP with a name that resolves in the previous curl command.
4. Update your widget in the Dashy conf to use any name in the SAN field that resolves to the server IP, rebuild Dashy, and let me know if you get an error.

You followed item 1 only which lead you to the certificate issue, which is what I initially suspected. Now that was fixed, and I assume the certificate you mounted in `/app/public/proxmox_ca.pem` is the new certificate. Now you need to make DNS resolution work for you using the `/etc/hosts` file, and to use the DNS name instead of the IP in the widget.

**Comment by CrazyWolf13** [comment] 2024-03-31 17:25
> You are not following my advice!!
> 
> Here is what you I suggest you do again: 1- Determine the Subject Alternative names of your server's certificate. You can do that by either inspecting the server certificate, or checking the certificates page in your PVE. 2. Make sure those DNS names resolve to the server IP in your network: You can try passing those names to the nslookup command, and the command should return the server IP. 3. Make sure those DNS names resolve to the server IP inside the Docker container. Here you might need to replace the IP with a name that resolves in the previous curl command. 4. Update your widget in the Dashy conf to use any name in the SAN field that resolves to the server IP, rebuild Dashy, and let me know if you get an error.
> 
> You followed item 1 only which lead you to the certificate issue, which is what I initially suspected. Now that was fixed, and I assume the certificate you mounted in `/app/public/proxmox_ca.pem` is the new certificate. Now you need to make DNS resolution work for you using the `/etc/hosts` file, and to use the DNS name instead of the IP in the widget.

Apologies for skipping this, I tought as the ip was listed as alternative name I could use that as well.

Here the requested steps:

Made sure that dns name resolve on the host:
![image](https://github.com/Lissy93/dashy/assets/96661824/f7edf026-f728-4e40-8f2f-2b68fada974f)


Made sure dns resolves inside the container:
![image](https://github.com/Lissy93/dashy/assets/96661824/1b81fb7d-c932-4fed-8eab-86a660449b98)

Updated the dashy conf:

Still not working, when disabling the cors proxy:
The following:
![image](https://github.com/Lissy93/dashy/assets/96661824/ac91e19e-e5ea-434b-8902-edd2d91bd404)


If I enable the cors proxy:
![image](https://github.com/Lissy93/dashy/assets/96661824/23c2172c-1b31-42c9-bad6-6179008562f2)

Thank you for the time so far!

**Comment by alayham** [comment] 2024-03-31 18:02
It seems that Dashy is still unable to resolve the name although you are able to resolve it on the shell. 

Anyway, I think this is a network issue and not related to Dashy or the widget. I am not familiar with your setup therefore my ability to help you is very limited.

The lesson from this issue is that the proxy should not crash if it gets an error. It should return the error message instead of the 500 crash, and that is a potential ticket for Dashy if someone is interested.

**Comment by CrazyWolf13** [comment] 2024-03-31 20:46
@ilium007 @ImChet @nortuzar @wnaude 
Were any of you able to get the widget to work?

**Comment by CrazyWolf13** [comment] 2024-05-12 12:22
@alayham 
Thanks for this awesome widget, after the recent changes, that headers in widgets do work again (https://github.com/Lissy93/dashy/issues/1549) , my widget is working and looks awesome!

**Comment by CrazyWolf13** [comment] 2024-05-12 12:22
As I got no Feedback from the others I'll close this ticket.

**Comment by CrazyWolf13** [comment] 2024-05-12 13:04
@alayham 

Sadly I have to reopen this.

The Widget seems to work for me -> It shows the noes all fine.
However when adding the following:

```
      - type: proxmox-lists
        useProxy: true
        options:
          cluster_url: https://lenovo1.{domain}.dev
          user_name: root@pam
          token_name: {token_name}
          token_uuid: {token}
        id: 1_688_proxmoxlists
```
```
      - type: proxmox-lists
        useProxy: true
        options:
          cluster_url: https://lenovo1.{domain}.dev
          user_name: root@pam
          token_name: {token_name}
          token_uuid: {token}
          node: lenovo1
          node_data: lxc
        id: 1_688_proxmoxlists
```

I get a empty widget with no errors in the browser console nor any error in networks tab, the CORS-Proxy request is green and the auth headers were present.


The Network tab shows the following response:
`{"data":[]}`

Have you got any idea here?
Did I miss out anything?

**Comment by alayham** [comment] 2024-05-17 15:09
The response you got means that the connection to the API was successful, Authentication was successful, but the result of your query is empty.
This can be either an authorization problem, for example, the token user is not authorized to get the data, or if the authorization is successful, the data for your query is empty.
In your case, I think the data is empty, most probably because the node name is wrong.

**Comment by CrazyWolf13** [comment] 2024-05-17 22:18
Thank you for the response!

Actually disabling Priviledge Seperation did the trick for me.
Maybe I'd be a good idea to include this into the docs, as it defaults to on.

**Closed by CrazyWolf13** 2024-05-17 22:18 UTC
Labels: 👤 Awaiting Maintainer Response
