### ISSUE TITLE
[FEATURE_REQUEST] Hosting Dashy on a different path

### ISSUE THREAD

**Issue by UltraBlackLinux** [Lissy93/dashy#1328] opened 2023-09-23 14:20 UTC
### Is your feature request related to a problem? If so, please describe.

I follow the philosophy of only using subdomains for entirely different servers. I want to host dashy on web.site/dashy, but the client still tries to get the files from web.site/, which is not where they are.

### Describe the solution you'd like

Add an environment variable (e.g. `WEBROOT`), where you can specify what dashy will prefix to all links.

(Priority is high because it's true for my use case, but I feel like this is a slight exaggeration. I might be able to implement this myself, but I have never worked with JS or anything web related, but I guess I could do some copy-pasting to do about what I want it to do)

### Priority

High (The app does not function without it)

### Is this something you would be keen to implement

Maybe

**Comment by UltraBlackLinux** [comment] 2023-12-23 10:07
bruh

**Comment by CrazyWolf13** [comment] 2024-04-21 18:02
Actually this is a duplicate of #1036 will close this.

**Closed by CrazyWolf13** 2024-04-21 18:02 UTC
Labels: 🦄 Feature Request, 👤 Awaiting Maintainer Response
