### ISSUE TITLE
[BUG] Still able to view homepage despite having cleared all cookies and session info while having an authorized user

### ISSUE THREAD

**Issue by shimizurei** [Lissy93/dashy#555] opened 2022-03-13 09:45 UTC
### Environment

Self-Hosted (Docker)

### Version

2.0.4

### Describe the problem

I'm trying to clear my cookies, local and session storage in attempt to fix the CSS issue I mentioned in the issue I created yesterday. I re-load the page and I'm not taken to my login page (`auth` is enabled). It looks like a guest access, but I don't have `appConfig.enableGuestAccess` enabled. I tried to rebuild the app, but since I'm not logged in, I can't. But I shouldn't even be able to see my homepage if I'm not logged in, right? It's quite weird. That's how it used to be before I updated to the latest version. BTW, also tested opening Dashy up in a guest window in Chrome (with no extensions or cookies), only to land on the homepage.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment] 2022-03-13 11:07
Thanks @shimizurei , and sorry abut that, have marked as high priority and will get sorted asap.

I think this issue is also caused by the required data not being initialised on time in the router

**Comment by FormBurden** [comment] 2022-03-22 20:55
Hi there, yes, I'm having the same issue. Thought I was doing something wrong, but it's pretty much the same config example with my own hash and user and all, and just logs as if you haven't enabled auth.

**Comment by Lissy93** [comment] 2022-03-27 19:19
This was fixed in #559 by @Ateroz 🙌 

A previous change was made where the config file could be read dynamically, therefore it was thought that the source wouldn't be needed in the Docker container, so to save space it was removed. However that meant that the config wasn't fetched on time for the router, causing a few issues including this one. Reverting part of those changes in #559 fixed this issue.

Apologies for the delay in replying, and the prior lack of an explanation.

**Closed by Lissy93** 2022-03-27 19:19 UTC
Labels: 🐛 Bug, ‼️ High Priority
