### ISSUE TITLE
link a txt file like a sticky note

### ISSUE THREAD

**Issue by zaromarco** [Lissy93/dashy#1281] opened 2023-08-15 18:39 UTC
### Is your feature request related to a problem? If so, please describe.

Please add a feature to add a note like a sticky note (postit) 
will be very usefull to have little remainder for a procedure to follow or something else
i think i can upload a txt file and link it via http command but it doesn't show opened in the dashboard

### Describe the solution you'd like

a yellow backgrond writeable like in windows OS

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None

**Comment by zaromarco** [comment] 2023-11-14 07:51
Any news?

**Comment by CrazyWolf13** [comment] 2024-02-03 21:03
Seems like a Duplicate of #636

Think this can be closed.

**Closed** 2024-02-11 15:12 UTC
Labels: 🦄 Feature Request, 👤 Awaiting Maintainer Response
