### ISSUE TITLE
[FEATURE_REQUEST] widget for uptime-kuma

### ISSUE THREAD

**Issue by dannymertens** [Lissy93/dashy#1459] opened 2024-02-05 19:17 UTC
### Is your feature request related to a problem? If so, please describe.

not really just nice to have

### Describe the solution you'd like

overview of the uptime kuma service 
https://github.com/louislam/uptime-kuma

My previous used dashboard had this option, would like to move to Dashy but missing this function

https://gethomepage.dev/latest/widgets/services/uptime-kuma/

![uptime](https://github.com/Lissy93/dashy/assets/46963011/982406ae-e2c8-449e-8528-db300affdabf)

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None

**Comment by CrazyWolf13** [comment] 2024-02-06 11:58
Duplicate of #1251 Please close this.

**Closed** 2024-02-11 15:13 UTC
Labels: 🦄 Feature Request, 👤 Awaiting Maintainer Response
