### ISSUE TITLE
[BUG] JavaScript heap out of memory

### ISSUE THREAD

**Issue by Lennys26** [Lissy93/dashy#834] opened 2022-08-07 14:10 UTC
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">System</h3>
<p dir="auto">Docker version 20.10.17</p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.1.1</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">Installation fails in all cases.</p>
<p dir="auto">I have attempted:</p>
<ul dir="auto">
<li><code class="notranslate">docker run -p 8080:80 lissy93/dashy</code></li>
<li><code class="notranslate">docker run -p 8082:80 --name dashy --restart=always --memory=1024m -e NODE_OPTIONS='--max-old-space-size=2048' lissy93/dashy</code></li>
</ul>
<p dir="auto">I have attempted on a Linode VM host with 1 CPU, 1GB RAM with very limited activity, and also on an RPI4, freshly installed/nothing else running.</p>
<h3 dir="auto">Additional info</h3>
<p dir="auto"><strong>Using TLDR <code class="notranslate">docker run</code></strong><br>
Using Dashy V-2.1.1. Update Check Complete<br>
<g-emoji class="g-emoji" alias="white_check_mark" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2705.png">✅</g-emoji> Dashy is Up-to-Date</p>
<ul dir="auto">
<li>Building for production...<br>
WARN  A new version of sass-loader is available. Please upgrade for best experience.</li>
</ul>
<p dir="auto">&lt;--- Last few GCs ---&gt;</p>
<p dir="auto">[61:0xb4541040]   113142 ms: Scavenge 221.6 (233.2) -&gt; 220.9 (235.5) MB, 6.0 / 0.0 ms  (average mu = 0.484, current mu = 0.411) allocation failure<br>
[61:0xb4541040]   114240 ms: Mark-sweep 223.0 (235.7) -&gt; 221.4 (236.2) MB, 1068.7 / 0.1 ms  (average mu = 0.349, current mu = 0.133) allocation failure scavenge might not succeed<br>
[61:0xb4541040]   115684 ms: Mark-sweep 223.7 (236.5) -&gt; 222.0 (237.0) MB, 1409.8 / 0.1 ms  (average mu = 0.195, current mu = 0.023) allocation failure scavenge might not succeed</p>
<p dir="auto">&lt;--- JS stacktrace ---&gt;</p>
<p dir="auto">FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory<br>
error Command failed with signal "SIGABRT".<br>
info Visit <a href="https://yarnpkg.com/en/docs/cli/run" rel="nofollow">https://yarnpkg.com/en/docs/cli/run</a> for documentation about this command.<br>
ERROR: "build-watch" exited with 1.<br>
error Command failed with exit code 1.<br>
info Visit <a href="https://yarnpkg.com/en/docs/cli/run" rel="nofollow">https://yarnpkg.com/en/docs/cli/run</a> for documentation about this command.</p>
<p dir="auto"><strong>Using "hacked" <code class="notranslate">docker run</code>:</strong></p>
<p dir="auto">Using Dashy V-2.1.1. Update Check Complete<br>
<g-emoji class="g-emoji" alias="white_check_mark" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2705.png">✅</g-emoji> Dashy is Up-to-Date</p>
<ul dir="auto">
<li>Building for production...<br>
WARN  A new version of sass-loader is available. Please upgrade for best experience.</li>
</ul>
<p dir="auto">&lt;--- Last few GCs ---&gt;</p>
<p dir="auto">[61:0xb45a0040]   116234 ms: Mark-sweep 223.2 (235.6) -&gt; 221.8 (236.1) MB, 1143.6 / 0.1 ms  (average mu = 0.243, current mu = 0.021) allocation failure scavenge might not succeed<br>
[61:0xb45a0040]   117683 ms: Mark-sweep 223.8 (236.1) -&gt; 222.4 (236.8) MB, 1422.6 / 0.1 ms  (average mu = 0.130, current mu = 0.019) allocation failure scavenge might not succeed</p>
<p dir="auto">&lt;--- JS stacktrace ---&gt;</p>
<p dir="auto">FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`</p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You have explained the issue clearly, and included all relevant info</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide <a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445"><img src="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445" alt="important" data-canonical-src="https://img.shields.io/badge/Important!-F6094E" style="max-width: 100%;"></a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://classic.yarnpkg.com/assets/og_image.png" width="48" align="right" />                          <div>          <strong>                          <a href="https://classic.yarnpkg.com/en/docs/cli/run/">Yarn</a>                      </strong>        </div>                    <div>Fast, reliable, and secure dependency management.</div>                      </blockquote>

**Comment by Lissy93** [comment] 2022-08-07 14:13
Don't forget to check the docs, troubleshooting and other tickets before opening a new issue.

This is covered in the troubleshooting guide in docs, see  [Troubleshooting Guide → Heap out of Memory](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#ineffective-mark-compacts-near-heap-limit-allocation-failed).

It's also a duplicate of #380, #350, #297, #349, #510 and #511.

**Closed by Lissy93** 2022-08-07 14:13 UTC
Labels: 🐛 Bug

**Comment by Lennys26** [comment] 2022-08-07 16:00
The troubleshooting guide (and the related, duplicate cases) indicates to add the `--memory=1024m` attribute. This was already done.

It appears that was got it to work for me was adding `--memory-swap=-1 --memory-swappiness=100`.
