### ISSUE TITLE
[BUG] statuscheck not display correctly on the Material / Material-dark and High-contrast-light themes

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#39] opened 2021-06-18 20:42 UTC
Hello,
I'm use Dashy in Docker 20.10.7 on OMV and in Debian 10. The problem is the same on both systems.
I also tried on Firefox / Chrome / Edge (up-to-date), same result.

I put in place statuscheck : 
![2021-06-18 22_32_35-Window](https://user-images.githubusercontent.com/45015615/122613744-a573f580-d085-11eb-9575-54034bf64839.png)

but it is not displayed correctly on 3 themes: 

Material : 
![2021-06-18 22_32_56-Window](https://user-images.githubusercontent.com/45015615/122613901-e4a24680-d085-11eb-89ae-360df2363e84.png)

Material-dark : 
![2021-06-18 22_33_07-Window](https://user-images.githubusercontent.com/45015615/122613921-ecfa8180-d085-11eb-80c1-3ee18666d0c3.png)

High-contrast-light : 
![2021-06-18 22_37_28-Window](https://user-images.githubusercontent.com/45015615/122613831-cb00ff00-d085-11eb-9b8a-3b48956a960f.png)

Thx you.

**Comment by Lissy93** [comment] 2021-06-19 13:09
Thanks for raising, that is indeed a bug. Looks like it's caused by the style overrides that I wrote for the affected themes, I'll fix it now :)

**Comment by Lissy93** [comment] 2021-06-19 13:22
Okay, I fixed and merged in PR #40 :)
It'll take half an hour or so the the CI to build and publish the new image.

Thanks for raising this, it helps me improve the app, and I'm very happy that someone is actually using it!
I haven't forgotten about your other issue, I'm going to re-do how the config is managed within the UI this weekend, which should fix that :)

**Closed by Lissy93** 2021-06-19 13:22 UTC
Labels: 🐛 Bug

**Comment by EVOTk** [comment] 2021-06-19 17:57
Thank-you for your prompt fix 
It is a pleasure to use Dashy!
