### ISSUE TITLE
Errors when editing through UI

### ISSUE THREAD

**Issue by LarryT8959** [Lissy93/dashy#1381] opened 2023-11-12 18:46 UTC
### Environment

Self-Hosted (Docker)

### System

Synology NAS / Docker

### Version

2.1.1

### Describe the problem

I posted about this a few days ago but now have more info. I've built a very nice dashboard that runs great. As long as I make all changes through the config file, everything is fine. When I make and save changes through the user UI, It corrupts the config file. I get validation warnings, sections should not have additional property:filtered items. I can see these errors when viewing through the user UI. As long as I don't save the file, the errors won't transfer the config file. The minute I save, then the errors show up in the file.
What am I missing?

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by MrCee** [comment] 2023-11-13 05:21
I am using docker also and this isn't a permissions problem for myself. 
I just wanted to add to this. If we are editing boolean in the UI >> Config >> Edit Config, and first option is `Write Changes to Config File`, we click okay and greeted by a success message in green. However nothing changes when viewing the file in terminal.
But... if you are to "Preview Changes" after this step, the dashboard displays in editing mode, and then with a further save here, you should be able to `Save to Disk` which will potentially update the config file which I have mapped as per: 

```
    volumes:
      - /volume1/docker/dashy/my-config.yml:/app/public/conf.yml
```

**Comment by codevski** [comment] 2024-01-15 23:03
getting the same thing:

![image](https://github.com/Lissy93/dashy/assets/1435321/15cc57fc-db4c-44d7-b2d1-7a11f8c70051)

But have no issues saving

**Comment by CrazyWolf13** [comment] 2024-02-03 10:08
Duplicate of #1361, please close this

**Closed** 2024-02-11 15:06 UTC
Labels: 🐛 Bug, 👤 Awaiting Maintainer Response
