### ISSUE TITLE
[BUG] Status Check : Server resulted ECONNREFUSED

### ISSUE THREAD

**Issue by Minatowalid** [Lissy93/dashy#1320] opened 2023-09-18 19:36 UTC
### Environment

Self-Hosted (Docker)

### Describe the problem

I'm having an issue with the Status Check.
I installed dashy and specified the port "127.0.0.1:4000:80" to work only on local I don't want to expose the app for external users.

![2023-09-18_20-13](https://github.com/Lissy93/dashy/assets/135609777/e9e340d6-390e-4c2d-b294-8613fe5cb8aa)

and any App i want to deploy it, I make the same thing in the port "127.0.0.1" to make it locally when I try to check the status in dashy i get this error : "service unavailable: Server resulted ECONNREFUSED (-111)"

![2023-09-18_20-30](https://github.com/Lissy93/dashy/assets/135609777/cb10e5c8-d89e-4fce-b6d0-56de07edcc33)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment] 2023-10-20 05:18
> ### Environment
> 
> Self-Hosted (Docker)
> 
> ### System
> 
> _No response_
> 
> ### Version
> 
> _No response_
> 
> ### Describe the problem
> 
> I'm having an issue with the Status Check.
> I installed dashy and specified the port "127.0.0.1:4000:80" to work only on local I don't want to expose the app for external users.
> 
> ![2023-09-18_20-13](https://github.com/Lissy93/dashy/assets/135609777/e9e340d6-390e-4c2d-b294-8613fe5cb8aa)
> 
> and any App i want to deploy it, I make the same thing in the port "127.0.0.1" to make it locally when I try to check the status in dashy i get this error : "service unavailable: Server resulted ECONNREFUSED (-111)"
> 
> ![2023-09-18_20-30](https://github.com/Lissy93/dashy/assets/135609777/cb10e5c8-d89e-4fce-b6d0-56de07edcc33)
> 
> 
> ### Additional info
> 
> _No response_
> 
> ### Please tick the boxes
> 
> - [X] You have explained the issue clearly, and included all relevant info
> - [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
> - [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
> - [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
> - [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

Why do you use 127.0.0.1:4000:80?
Why two ports?

**Comment by Minatowalid** [comment] 2023-10-20 17:11
@CrazyWolf13 
it's only 1 port.
normally you will use "4000:80" but anyone in your network can access to the website by using your ip and the port
adding "127.0.0.1" making it work only locally so no one can access to your dashy.
I hope it makes sense to you now.

**Comment by CrazyWolf13** [comment] 2023-10-20 20:30
> @CrazyWolf13 
> it's only 1 port.
> normally you will use "4000:80" but anyone in your network can access to the website by using your ip and the port
> adding "127.0.0.1" making it work only locally so no one can access to your dashy.
> I hope it makes sense to you now.

Oh okay.
Yeah surely did know about 127.0.0.1 but not about the port.

**Comment by Minatowalid** [comment] 2023-10-20 21:34
@CrazyWolf13 
if you are familiar with docker you will know that.

"4000:80" mean that the first port "4000" is the host machine's port, that what you will use to access your dashy. Any traffic that comes to this port on your host machine will be forwarded to the container.

And "80" This is the container's port. It's the port where your application inside the Docker container is listening for incoming network requests.

So, when you use 4000:80, it means that the Docker container is set up in a way that any requests made to port 4000 on your host machine will be redirected to port 80 inside the container. This is useful because it allows you to run multiple containers on your host, each using port 80, but with different host port mappings.

I recommend you to read more about docker to understand.

**Comment by Lissy93** [comment] 2023-10-20 21:57
There's a section in the Troubleshooting guide about [Failing Status Checke](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#status-checks-failing) that you might find helpful.

My guess is this is either a misconfiguration or a CORS error. There's also bunch of extra [Status Check Settings](https://github.com/Lissy93/dashy/blob/master/docs/status-indicators.md) you can use to (hopefully!) get it working for your use case.

But as @Minatowalid pointed out, that's your docker-compose, rather than your Dashy config. If you can share the config file, that'll help. Also if you pop open the browser console, you should see some more details about the error there ([here's how](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console) if your unsure).

**Comment by Lissy93** [comment] 2023-10-20 22:02
I'm going to close this ticket, as the issue template isn't properly filled in so there's not enough info for me to look into it.

Failing status checks is quite a common issue, and usually caused by the server config for the service your trying to check the status of (CORS), or a mistake in your Dashy config.  

For future reference, try and include the relevant parts of your config, and any logs, as well as fill in the issue template.

If you can provide the extra info - feel free to comment below, and I'll try and help, or re-open this ticket if needed.

**Closed by Lissy93** 2023-10-20 22:02 UTC
Labels: 🐛 Bug

**Comment by CrazyWolf13** [comment] 2023-10-21 05:48
Ohh I get that just now!

Yeah sure I know docker very good.

Didn't know what I was thinking back at this morning, maybe it was a bit too early 😆

**Comment by Minatowalid** [comment] 2023-10-21 16:39
@Lissy93
here is the conf.yml I convert it to txt so I can upload it here
[conf.txt](https://github.com/Lissy93/dashy/files/13061234/conf.txt)

and here is the console logs
[console-export.txt](https://github.com/Lissy93/dashy/files/13061235/console-export.txt)
