### ISSUE TITLE
Environment variable `BASE_URL` has no effect

### ISSUE THREAD

**Issue by errestan** [Lissy93/dashy#1398] opened 2023-11-25 18:06 UTC
### Environment

Self-Hosted (Docker)

### System

Ubuntu: 22.04 Docker: 24.0.7 Docker Compose: 1.29.2

### Version

2.1.1

### Describe the problem

The `BASE_URL` environment variable has no effect. I'm attempting to run Dashy at: http://localhost:4000/dashy but while the initial page starts loading it is unable to retrieve resources because the URLs used for CSS and scripts do not contain the sub-directory.

My stripped down Docker compose file is as follows:
```
---
version: '3.8'

services:
  app:
    image: lissy93/dashy
    ports:
      - 4000:80
    environment:
      - BASE_URL=/dashy
```
When access via: http://localhost:4000/ everything works as expected. But If accessed via http://localhost:4000/dashy I get a 404. If I add labels to use Traefik as a reverse proxy I can then reach the page but the page can not load CSS etc.

Apologies If I've missed something obvious. I've read through a good amount of the documentation and read a few bug reports of people trying to do something similar but I've been unable to solve this issue. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment] 2024-02-03 10:01
Already know, Please look through the issues and knows problems before submitting a issue.

Duplicate of #1036 Please close this.

**Closed** 2024-02-11 15:03 UTC
Labels: 🐛 Bug, 👤 Awaiting Maintainer Response
