### ISSUE TITLE
Trying to Change Page Title

### ISSUE THREAD

**Issue by songyp0505** [Lissy93/dashy#1429] opened 2024-01-03 07:06 UTC
### Discussed in https://github.com/Lissy93/dashy/discussions/1156

<div type='discussions-op-text'>

<sup>Originally posted by **djfreakthefirst** April  2, 2023</sup>
Please help.  I've been at this for 8 hours.  Very frustrated.

All I want to do is change the word Dashy in the broswer tab.  I have crawled through every file in the /app/ folder in the docker instance and I have changed Dashy out in every single .json and .html I can find. I have changed it in the GUI.  I've changed it absolutely everywhere I can find.

I am no longer using my cloudflare tunnel.  All of this work is now happening via local IP so I know that's not the issue.

Someone please tell me how to change this config setting.  I have my name popping up during initialization but then when the page loads it goes back to Dashy.  I've cleared the browser cache more times than I can count now.

I'd be eternally grateful for any help in changing this setting.  I'm not referring to the page heading.  I'm talking about the TITLE that shows up in the tabs or in the tabs view in iOS.

Thank you in advance for any help.</div>

**Comment by CrazyWolf13** [comment] 2024-02-05 12:06
Possible Duplicate of #1234

**Closed** 2024-02-11 15:13 UTC
Labels: 👤 Awaiting Maintainer Response
