### ISSUE TITLE
[BUG] OpenID redirect not triggered for index.html

### ISSUE THREAD

**Issue by Kirkland-gh** [Lissy93/dashy#1539] opened 2024-04-21 02:21 UTC
### Environment

Self-Hosted (Docker)

### System

Docker

### Version

3.0.0

### Describe the problem

When I load / (index.html) I see the dashy loading page. 

![Screenshot 2024-04-20 at 10 16 39 PM](https://github.com/Lissy93/dashy/assets/56662961/fef04faf-5549-452f-88b0-4c992bcd6214)

If I manually navigate to dashy.domain.com/login I am redirected to my OpenID url where I can authenticate and am redirected back. It was required to update my Valid redirect URIs in keycloak settings to get this to work.  
 
the part of my appConfig related to auth
```
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: true
    keycloak:
      serverUrl: https://keycloak.example.com
      realm: example-realm
      clientId: example-clientid
      legacySupport: false
  ```
  
  I would like the redirect to happen when I load dashy.example.com/ 
  
  

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment] 2024-04-21 22:01
So just to clarify, you want `http://[dashy].local` to redirect to `http://[dashy].local/login` if not yet authenticated and KC is enabled?

**Comment by Kirkland-gh** [comment] 2024-04-21 22:06
If enableGuestAccess: false, yes.

**Comment by Kirkland-gh** [comment] 2024-04-21 22:09
Or I suppose some indication of how someone should login to get access to the page without just knowing they need to go to /login. A login button with a notification that you are not authorized yet would work as well.

**Comment by Kirkland-gh** [comment] 2024-04-29 04:28
tested on 3.0.1 and this issue is still present.

**Comment by Lissy93** [comment] 2024-04-29 14:19
Closing as duplicate of #1538

**Closed by Lissy93** 2024-04-29 14:19 UTC
Labels: 🐛 Bug, 👤 Awaiting Maintainer Response
