### ISSUE TITLE
[BUG] After update Dashy is not authenticating and guest mode is always on

### ISSUE THREAD

**Issue by saint11** [Lissy93/dashy#1126] opened 2023-03-01 08:24 UTC
### Environment

Self-Hosted (Docker)

### System

Docker  20.10.18

### Version

2.1.1

### Describe the problem

When opening my dashboard I noticed that I wasn't logged in (I couldn't change anything) but I could see my links, even if I tried manually setting `enableGuestAccess: false` on config.yml.

I tried hideForGuests: true in a couple sessions too, that cause the whole browser screen to disappear.

Rolling back to 2.1.0 fixed the problem.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by pabloalcantara** [comment] 2023-03-02 17:05
Same bug on 2.1.1, revert to 2.1.0 and authentications works again

**Comment by psychic69** [comment] 2023-03-12 03:30
The issue is that if a user is not logged on in 2.1.1 it will allow one to go to the base / URL and it won't enforce /login like 2.0.1.  I reverted for now this is an unreliable auth method in the meantime.

**Comment by liquidthex** [comment] 2023-04-02 03:32
I am experiencing this, as well.

**Comment by MadDirtMonkey** [comment] 2023-04-03 15:41
Same problem here, working fine when I roll back to 2.1.0

**Comment by stevenmccall** [comment] 2023-04-04 00:44
I had the same issue updating to 2.1.1, but rolling back to 2.1.0 did not resolve the issue. I had to roll back to 2.0.0 to get the login working again. It had been a while since the docker was updated, maybe there was some intermediate change to the config that was not checked in 2.1.0 that leads to a similar issue as this 2.1.1 bug.

**Comment by CaptainSanders** [comment] 2023-05-05 07:56
Any update on this?

**Comment by mfnalex** [comment] 2023-06-21 09:01
I got a similar issue on 2.1.1 - adding the appConfig.auth section with one user and setting enableGuestAccess to false doesn't do anything - I don't get any login screen, manually going to /login redirects to the dashboard, and all links are visible, even those that are hidden for guests.

**Comment by mfnalex** [comment] 2023-06-21 09:10
I just noticed that the whole authentication thing seems to work when setting enableGuestAccess to true, but not when it's set to false

**Comment by zell-mbc** [comment] 2023-06-26 07:57
Unfortunately not for me. All versions higher than v2.1.0 break the login for me, no matter what `enableGuestAccess` is set to.

**Comment by sr-as2** [comment] 2023-06-28 14:35
Have the same problem!
Hope it will be be resolved soon!

**Comment by Jefffish09** [comment] 2023-07-23 14:28
Same issue.
Hope to release a new version to fix it.

**Comment by TheRealGramdalf** [comment] 2024-01-10 06:11
I believe I found the issue - see https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 for a full writeup.

**Comment by CrazyWolf13** [comment] 2024-03-03 17:36
Hi
This problems seems to be related to dashy not automatically rebuilding on changes, see #1479 and https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 
A new release has just been published, which should fix this issue, so please upgrade to the latest version.
If this is not the case just respond back to this ticket and I'll reopen this issue.
Thanks and have a nice day.

**Closed by CrazyWolf13** 2024-03-03 17:36 UTC
Labels: 🐛 Bug, 📌 Keep Open

**Comment by zell-mbc** [comment] 2024-03-03 19:28
Docker not yet updated?
`% sudo docker compose up -d && sudo docker compose logs -f
[+] Running 1/1
 ✘ dashboard Error                                                                                1.8s 
Error response from daemon: manifest for lissy93/dashy:2.1.2 not found: manifest unknown: manifest unknown
`

**Comment by CrazyWolf13** [comment] 2024-03-03 19:32
> Docker not yet updated? `% sudo docker compose up -d && sudo docker compose logs -f [+] Running 1/1 ✘ dashboard Error 1.8s Error response from daemon: manifest for lissy93/dashy:2.1.2 not found: manifest unknown: manifest unknown `
> 
> I tried `latest` as well but that still gives me 2.1.1

https://github.com/Lissy93/dashy/discussions/1484#discussioncomment-8658525
