### ISSUE TITLE
[BUG] Extremely high CPU usage on and after start

### ISSUE THREAD

**Issue by elendil7** [Lissy93/dashy#1665] opened 2024-08-10 22:56 UTC
### Environment

Self-Hosted (Docker)

### System

Arm/64

### Version

latest

### Describe the problem

Startup takes a lot of CPU, until the /dist directory is built. This was not the case in previous versions (quite a while back now). Was wondering if its possible to remedy by caching some things / including them in the docker image?

![image](https://github.com/user-attachments/assets/aba7abf8-0e2c-4f5a-8d06-416a75339790)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment] 2024-08-11 06:31
Duplicate of https://github.com/Lissy93/dashy/issues/1585

**Closed** 2024-08-11 06:31 UTC
Labels: 🐛 Bug, 🕸️ Duplicate
