### ISSUE TITLE
[BUG] Authentication settings cannot be saved to a configuration file

### ISSUE THREAD

**Issue by LonginusL33T** [Lissy93/dashy#1498] opened 2024-03-05 09:56 UTC
### Environment

Self-Hosted (Docker)

### System

Windows 10,Docker Desktop 4.27.2,Edge 122.0.2365.66,Docker Engine 25.0.3

### Version

2.1.2

### Describe the problem

In the latest version, setting a username and password still cannot be saved in the configuration file. Even if I do a manual rebuild or restart docker I still can't get to the login screen

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment] 2024-03-05 11:38
Closing as duplicate of #990

**Closed by Lissy93** 2024-03-05 11:38 UTC
Labels: 🐛 Bug
