### ISSUE TITLE
[QUESTION] <Authentication Issue>

### ISSUE THREAD

**Issue by jmc5105** [Lissy93/dashy#1388] opened 2023-11-15 19:02 UTC
<h3 dir="auto">Question</h3>
<p dir="auto">Hi,<br>
I've followed the deployment steps for setting up authentication within the conf.yml file.  Unfortunately, the username and password fields never prompt and the dashboard always immediately loads.</p>
<p dir="auto">Any assistance would be very much appreciated.</p>
<p dir="auto">Thanks!</p>
<p dir="auto">Here's what t he top of my conf.yml file looks like:</p>
<p dir="auto">`appConfig:<br>
layout: auto<br>
iconSize: medium<br>
theme: material-dark-original<br>
auth:<br>
users:<br>
- user: test<br>
hash: 9b8sdfs34hd4567fl690820f56b31ac48807f9bf5c.....<br>
type: admin</p>
<p dir="auto">pageInfo:<br>
title: Life Amongst The Ferns<br>
description: Welcome Home Josh!<br>
navLinks:<br>
- title: GitHub<br>
path: <a href="https://github.com/Lissy93/dashy">https://github.com/Lissy93/dashy</a><br>
target: newtab<br>
- title: Documentation<br>
path: <a href="https://dashy.to/docs" rel="nofollow">https://dashy.to/docs</a><br>
target: newtab<br>
footerText: ''`</p>
<h3 dir="auto">Category</h3>
<p dir="auto">Configuration</p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy (check the first two digits of the version number)</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">question hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://repository-images.githubusercontent.com/343078060/82f850a2-b1af-4e9f-9245-c92700d74856" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/Lissy93/dashy">GitHub - Lissy93/dashy: 🚀 A self-hostable personal dashboard built for you. Includes status-checking, widgets, themes, icon packs, a UI editor and tons more!</a>                      </strong>        </div>                    <div>🚀 A self-hostable personal dashboard built for you. Includes status-checking, widgets, themes, icon packs, a UI editor and tons more! - GitHub - Lissy93/dashy: 🚀 A self-hostable personal dashboard ...</div>                      </blockquote><blockquote>                                <div>          <strong>                          <a href="https://dashy.to/docs">Dashy | Dashy</a>                      </strong>        </div>                    <div>Documentation | Dashy, a self-hosted dashboard for your homelab</div>                      </blockquote>

**Comment by cszhe** [comment] 2023-11-16 04:03
Samething here, running with docker. works with 2.1.0, which is pretty old.

**Comment by jmc5105** [comment] 2023-11-16 17:51
It's good to know I'm not the only one. :)

**Comment by Kirkland-gh** [comment] 2023-11-19 16:04
Likely duplicate of https://github.com/Lissy93/dashy/issues/990

**Comment by Lissy93** [comment] 2024-02-11 15:05
I'm going to close as a dup of #990, follow that ticket instead for updates

**Closed** 2024-02-11 15:04 UTC
Labels: 🤷‍♂️ Question, 👤 Awaiting Maintainer Response
